endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  refresh:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client: 
    initialInstanceInfoReplicationIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  server: 
    response-cache-update-interval-ms: 5000

eventBus:
  broker: redis
  redisHost: localhost
  redisPort: 6379
  redisTopic: csrt-event-bus

ribbon: 
  serverListRefreshInterval: 1000

#spring:
#  rabbitmq:
#    host: 192.168.99.100
#    port: 9001

logging:
  level:
    root: WARN
    com.amex: DEBUG
